### ISSUE TITLE
[BUG] The presence of this plugin breaks...line breaks in mkdocs

### ISSUE THREAD

**Issue by rmscode** [jfcmontmorency/mkdocs-audio#1]
As we all probably know, mkdocs respects HTML line break tags. Anyone of the following will work:

- `<br>`
- `</br>`
- Double space at the end of the line

For whatever reason, this plugin prevents mkdocs from adding line breaks to the final HTML after running `mkdocs build`, but only for the "closed" version of the tag (`</br>`)

_This . . ._

```
Line 1</br>
Line 2<br>
Line 3 (Double space)     
Line 4
```

_Produces this . . ._

```
Line 1 Line 2
Line 3
Line 4
```

You can see that the line break missing from the final html:

![image](https://github.com/user-attachments/assets/4ea3596e-5614-46ce-9b49-b7226ddbdf97)

This is easy to reproduce. Install a fresh instance of mkdocs with the mkdocs-audio plugin active.

**Comment by jfcmontmorency** [comment]
Ill take a look at it

**Comment by rmscode** [comment]
Proposed a fix in #2

**Comment by jfcmontmorency** [comment]
Merged. Thanks for the contribution

**Comment by rmscode** [comment]
Don't forget to update the PyPI project :P

**Comment by jfcmontmorency** [comment]
There you go 
https://pypi.org/project/mkdocs-audio/

**Comment by rmscode** [comment]
I was thinking about this a bit more today after a colleague had asked me why I did my line breaks this way (single `</br>`). I didn't really have an answer for that...Just a habit I formed some time ago. Technically, a single `</br>` tag is incorrect HTML syntax but for all these years, I can't recall running into trouble by doing it that way. At least not while writing markdown. 

Perhaps it was forgiving processors. Apparently, some markdown processors are pretty lenient and do not strictly enforce HTML syntax rules. You can see that even GitHub respects the incorrect syntax (First Line`</br>`Next line):

First Line</br>Next line

Anyway, I brought this up because maybe you'd want to consider removing my [contribution](#2) from your code? Technically speaking, there was nothing about your plugin or lxml that broke _proper_ line breaks. In fact, in XML, line breaks must be closed either by using `<br />` or both open and closed tags together. The inclusion of lxml in your plugin must be imposing stricter syntax rules. 

I've already done some testing to ensure that using both the open and closed tags together (First Line`<br>`Next Line`</br>`) work with your plugin, so it's safe so remove my code if you wish. Unless a single `</br>` is something that is commonly used among people who write markdown but aren't necessarily concerned with proper HTML/XML syntax in that regard.

Cheers.
